service: no-devices-nodejs-lambda

frameworkVersion: "2"

package:
  include:
    - index.js
    - smartapp.js
    - locales/**
  exclude:
    - .git/**
    - .gitignore
    - payloads/**
    - CONTRIBUTING.md

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

  # replace with closest region to your geographic location for ideal latency
  # see: https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
  region: us-east-1

functions:
  smartapp:
    handler: index.handle
    timeout: 10
